* Config/Preamble :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliography
# #+LATEX_HEADER: \DeclareNameAlias{sortname}{last-first}
#+LATEX_HEADER: \DeclareNameAlias{sortname}{given-family}
#+LATEX_HEADER: \addbibresource{aidan.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=biber, sorting=nyvt, style=authoryear, firstinits]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=natbib, giveninits=true]{biblatex}
#+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=false,giveninits=true,hyperref]{biblatex}

** Exporter Settings
#+AUTHOR: Joseph Pfeifer
#+EXPORT_FILE_NAME: ./lebenslauf-pfeifer.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Joseph Pfeifer}
\photoR{2.8cm}{joseph_portrait.jpeg}
\tagline{Software Entwickler}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  \homepage{}
  \email{joseph.p.pfeifer@gmail.com}
  \phone{+43 6763800492}
  \location{Krobotek AT}
  \github{jbpfeifer}
  \linkedin{joseph-pfeifer/}
  \dob{21 Juni 1980}
  \driving{A, B}
}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{2}
#+end_export
** Personal Statement :ignore:
#+begin_export latex
 \begin{quote}
 ``Ich beschäftige mich gerne mit neuen Technologien in der IT und setze gerne Ideen um. Wenn ein Problem besteht arbeite ich vebissen daran''
 \end{quote}
#+end_export
** Erfahrung
*** Senior Fullstack Developer                                       :ignore:
{{{cvevent(Senior Fullstack Developer, markta GmbH,Juni 2020 -- , Wien\, AT)}}}

# Researching methods for probabilistic inference and control in multimodal dynamical systems. EPSRC Centre for Doctoral Training in Future Autonomous and Robotic Systems (FARSCOPE).
Entwicklung und Adaption von Odoo Modulen um die Geschätsprozesse marktas in Odoo abzubilden
 - Vue Storefront Modul
 - Klarna Modul
 - Mailchimp Modul
 - Anbindung an ein prorietäres Lagerverwatungssystem unseres Fullfilment Providers
 - Rest Modul

Entwicklung und Implementierung von Vue Storefront

Entwicklung aber v.a Security Updates des Mageto 2 Stores

{{{cvtag(odoo)}}}
{{{cvtag(REST)}}}

*** Fullstack Developer                                              :ignore:
{{{par-div}}}
{{{cvevent(Fullstack Developer, markta GmbH,Februar 2019 -- Juni 2020, Wien\, AT)}}}

- Odoo
- Magento 2
- Aufbau eines Fullfilment Centers  

{{{cvtag(Communication)}}}
{{{cvtag(Active listening)}}}
{{{cvtag(Teaching)}}}

*** Sys Admin und Magento 2 Developer                                :ignore:
{{{par-div}}}
{{{cvevent(Magento2 Developer, markta GmbH, Februar 2018 -- Februar 2019, Wien\, AT)}}}

# I worked as a mechanical engineer within the building services division where I developed my
# teamwork skills and learned the importance of knowledge management.
# I was in charge of optimising the heating, ventilation and air-conditioning of a building a
# Hackney Wick underground station.
# I met with external architects to communicate our ideas and I personally overcame logistical issues
# and improved a systems efficiency, resulting in the designs approval.
# I consistently met deadlines whilst working under pressure and was offered future employment.
# This internship strengthened my desire to move away from engineering and pursue a research driven
# career involving mathematics and programming.

- Developed teamwork skills, learning the importance of knowledge management within a team.
- Overcame logistical issues and improved a system’s efficiency, resulting in the design’s approval.
- Consistently met deadlines whilst working under pressure.
  
{{{cvtag(Engineering)}}}
{{{cvtag(Teamwork)}}}
{{{cvtag(Industry)}}}

*** CEO Lokale Sachen                                                :ignore:
{{{par-div}}}
{{{cvevent(CEO Lokale Sachen, mw, Juni -Juli 2019, Krobotek\, AT)}}}
 - Alles da

** Projects :noexport:
*** Active Learning :ignore:

# {{{cvevent(Investigating Exploration-Exploitation in Multimodal Dynamical Systems (Academic), University of Bristol, May 2021 - Ongoing, Bristol\, UK)}}}
{{{cvevent(Exploration of Operatable Dynamics Modes in Multimodal Dynamical Systems, University of Bristol, May 2021 - Ongoing, Bristol\, UK)}}}

- Developing data-efficient techniques for exploration in multimodal dynamical systems.
- The goal of this project is to explore a single dynamics mode that is known to be operatable whilst avoiding other modes.
  # unoperatable capable of remaining in a single dynamics mode during exploration.

# {{{cvtag(JAX)}}}
{{{cvtag(Bayesian optimisation)}}}
{{{cvtag(Gaussian processes)}}}
{{{cvtag(Optimal control)}}}

** Newpage :ignore:
{{{new-page}}}

** Newpage :ignore:noexport:
{{{new-page}}}

** Volunteering :noexport:
*** FARSCOPE Course Rep :ignore:
{{{cvevent(Cohort Representative, FARSCOPE CDT, Sept 2018 - Ongoing, Bristol\, UK)}}}
# - I represent myself and fellow CDT students in management meetings where I communicate ideas and information between students and management.
- Represent myself and my CDT peers in management meetings.
- Communicate information between students and management.

{{{cvtag(Communication)}}}
{{{cvtag(Interpersonal Skills)}}}

{{{par-div}}}

*** Code Club :ignore:
{{{cvevent(Club Leader, Code Club, Dec 2017 - April 2018, Junction 3 Library\, Bristol \, UK)}}}

# - I collaborated with [[https://codeclub.org/en/][Code Club]] and Bristol Libraries to set up and run a Code Club for young people aged 9-13.
# - Demonstrating my abi involved organising,  planning lessons and teaching
- Set up (and then ran) a [[https://codeclub.org/en/][Code Club]] for children aged 9-13.
- Led the organisation, planning and teaching of weekly lessons.
- Planned lessons to engage children by making coding fun.
- Extremely rewarding and reinforced my love for teaching.
# - @ Junction 3 Library in Easton, Bristol.

{{{cvtag(Leadership)}}}
{{{cvtag(Teaching)}}}
{{{cvtag(Communication)}}}
{{{cvtag(Active listening)}}}

*** Drivetrain :ignore:noexport:
{{{par-div}}}

{{{cvevent(Technical Lead (Drivetrain), Formula Student, Jan 2015 - Jan 2016, Bristol\, UK)}}}

Each year, as part of Formula Student, students design, build and race a single seat race car.
- Finished 2nd in the National Class 2 competition in 2013/2014, I was then selected as the Drivetrain lead.
- This role improved my communication skills as I was leading weekly presentations.
- I developed my leadership skills through setting realistic objectives, effectively allocating work to the appropriate team members and monitoring outcomes.

{{{cvtag(Teamwork)}}}
{{{cvtag(Leadership)}}}
{{{cvtag(Time Management)}}}

*** Snowboard Captain :ignore:noexport:
{{{par-div}}}

{{{cvevent(Snowboard Captain, University of Bristol Snowsports Club, Jan 2014 - Sept 2015, Bristol\, UK)}}}

- Organised multiple weekly training sessions, demonstrating my ability to plan and run events smoothly.
- Negotiated competitive prices for a growing member base within an inherently expensive sport.
- Responsible for aiding the smooth running of the club and helping to organise the annual university ski trip, with circa 1500 participants, working under pressure to manage people in high stress situations.
- Awarded the ‘Team of the Year’ award and full colours for my performances and contributions to the sport.

{{{cvtag(Teamwork)}}}
{{{cvtag(Leadership)}}}
{{{cvtag(Time Management)}}}

* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export

** Skills
{{{cvtag(Python)}}}
{{{cvtag(TensorFlow)}}}
{{{cvtag(Odoo)}}}
{{{cvtag(Jupyter)}}}
{{{cvtag(NumPy)}}}
{{{cvtag(SciPy)}}}
{{{cvtag(Matplotlib)}}}

{{{divider}}}

{{{cvtag(PHP)}}}
{{{cvtag(Magento2)}}}
{{{cvtag(MATLAB)}}}
{{{cvtag(ROS)}}}

{{{divider}}}

{{{cvtag(Javascript)}}}
{{{cvtag(node)}}}
{{{cvtag(VUE)}}}
{{{cvtag(Vue Storefront)}}}
{{{cvtag(React Native)}}}

{{{divider}}}

{{{cvtag(Git/GitHub)}}}
{{{cvtag(HTML)}}}
{{{cvtag(CSS)}}}

** Ausbildung

{{{cvevent(Lehramt Mathematik und Sport, PH Niederösterreich, Sept 2010 - Juni 2013,)}}}

{{{divider}}}

{{{cvevent(Psychologie, Universität Wien, Aug 2002 - Sept 2008,)}}}

{{{divider}}}

{{{cvevent(Gymnasium, Ried im Innkreis, Sept 1990 -- Juni 1999,)}}}

{{{divider}}}

** Newpage :ignore:
#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT

** My Life Philosophy :noexport:
#+begin_export latex
% \begin{quote}
% ``Something smart or heartfelt, preferably in one sentence.''
% \end{quote}
#+end_export

# ** Most Proud Of :ignore:
# #+begin_export latex
# \cvsection{Most Proud of}
# #+end_export

# #+begin_export latex
# \cvachievement{\faTrophy}{Code Club Leader}{Collaborated with Code Club and Bristol Libraries to set up and run a Code Club for 9-13 year olds.}
# #+end_export

# #+begin_export latex
# \divider

# \cvachievement{\faHeartbeat}{British University Snowboard Slalom Champion}{Won all national British university slalom competitions in 2017-2018.}
# #+end_export

** Achievements :noexport:
{{{cvachievement(\faTrophy, Full Sporting Colours, Awarded full colours for outstanding achievements in snowboarding. Multiple gold medals in British University Snowboard Championships.)}}}

{{{divider}}}

{{{cvachievement(\faCertificate, Starting To Teach, Established myself as a confident\, enthusiastic and effective teacher who is able to engage\, encourage and develop students' learning.)}}}

{{{divider}}}

{{{cvachievement(\faTrophy,Bristol Plus Award, For undertaking a wide range of tasks to further enhance student skills - only 700 out of 23\,000 achieved this award per annum.)}}}

{{{divider}}}

{{{cvachievement(\faCertificate, Mary Jones Prize for Mathematics, For outstanding achievements in A Level mathematics @ Ripon Grammar School)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, The Duke of Edinburgh's Award, Bronze/Silver/Gold)}}}

** Languages :ignore: 
#+begin_export latex
\cvsection{Sprachen}

\cvskill{Deutsch}{5}
\divider

\cvskill{Englisch}{5}
\divider

\cvskill{Italienisch}{3}

% %% Yeah I didn't spend too much time making all the
% %% spacing consistent... sorry. Use \smallskip, \medskip,
% %% \bigskip, \vpsace etc to make ajustments.
% \medskip
#+end_export

\newpage
** References :noexport:
#+begin_export latex
% \cvref{name}{email}{mailing address}
\cvref{Prof.\ Arthur Richards}{University of Bristol}{arthur.richards@bristol.ac.uk}
% {Address Line 1\\Address line 2}
\divider
\cvref{Dr.\ Carl Henrik Ek}{University of Cambridge}{che29@cam.ac.uk}
% {Address Line 1\\Address line 2}
#+end_export

* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export



